apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dragonfly-operator
  namespace: flux-system 
spec:
  interval: 10m
  chart:
    spec:
      chart: dragonfly-operator
      version: "v1.1.7" 
      sourceRef:
        kind: HelmRepository
        name: dragonfly-operator
        namespace: flux-system