apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  labels:
    app: dragonfly-lesson13
  name: dragonfly-lesson13
  namespace: krotovhh
spec:
  replicas: 1
  imagePullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 500m
      memory: 500Mi
    limits:
      cpu: 1000m
      memory: 1024Mi